# Generated by Django 4.1 on 2023-02-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='work',
        ),
        migrations.AddField(
            model_name='artist',
            name='works',
            field=models.ManyToManyField(to='project1.work'),
        ),
    ]
